### PR TITLE
Feat/add messages elide

### PR DESCRIPTION
**Pull request by asimsedhain**
Adding on top of this [PR](https://github.com/asimsedhain/solace-rs/pull/10)

### CODE REVIEW

**Comment by ianplut** [comment]
@asimsedhain I would like to use the cache features of solace.  Have you really not tested any of it?

**Comment by ianplut** [comment]
> Adding on top of this [PR](https://github.com/asimsedhain/solace-rs/pull/10)

Nice

**Comment by asimsedhain** [comment]
@ianplut I have tested it locally and it has worked as expected. By untested, I mean this repo does not contain any integration tests or load tests for the cache feature.

lmk if you find any!

**Comment by ianplut** [comment]
I'm trying it now

**Pull request merged**
